apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dvwa_crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dvwa_cr
subjects:
- kind: ServiceAccount
  name: dvwasa
  namespace: dvwa